# Site settings
title: Catherine Gitau
description: A blog about Catherine Gitau 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi! I'm Catherine.
user_description: I'm Catherine Gitau,a final year student at the Jomo Kenyatta University of Agriculture and Technology pursuing a degree in Mathematics and computer science,majoring in statistics.Started off as a web developer creating simple websites during my free time,and slowly transitioned into a data scientist mid 2016.Been learning about data science tools till date and my passion for getting insights through data has gradually grown since then.This website will display some of the projects I have done.Welcome and Make sure you check out my blog!
user_title: web developer and self taught Data scientist
email: catherinegitau94@gmail.com
twitter_username: swtkatelyn
github_username:  CateGitau
gplus_username:  Katelyn Sonnie

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
