# Site settings
title: Catherine Gitau
description: A blog about Catherine Gitau 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Catherine Gitau
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Web developer and a Budding Data Scientist
email: catherinegitau94@gmail.com
twitter_username: swtkatelyn
github_username:  CateGitau
gplus_username:  CateGitau

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
